// Probe 3: pod12 Poseidon bit-exact verification
//
// Dispatches a Metal kernel that runs the full Poseidon12 permutation (pod12)
// on ~1000 seeded random 12-element inputs. Results are compared bit-exact
// against the CPU PoseidonGoldilocks::hash_full_result_seq oracle.
//
// The MSL kernel source (poseidon.metal) is compiled at runtime via
// newLibraryWithSource:options:error: — no precompiled .metallib needed.
// constants.metal.inc is generated by Part 3; this probe reads it at runtime.
//
// Build:
//   clang++ -std=c++17 -O0 -fobjc-arc -ObjC++ -framework Metal -framework Foundation \
//     -I../../src -DMTL_KERNEL_DIR="../../src/metal/kernels" \
//     probe_poseidon.mm -o probe_poseidon
// Run:
//   ./probe_poseidon
// Exit 0 on full bit-exact match; exit 1 on first mismatch.

#import <Foundation/Foundation.h>
#import <Metal/Metal.h>

#include <cstdio>
#include <cstdint>
#include <cstring>
#include <vector>
#include <fstream>
#include <sstream>
#include <random>

// CPU oracle
#define GOLDILOCKS_ARCH_GENERIC 1
#include "goldilocks_base_field.hpp"
#include "goldilocks_base_field_scalar.hpp"
#include "poseidon_goldilocks.hpp"

// ----- RNG -------------------------------------------------------------------
static std::mt19937_64 rng(0xCAFEBABEDEAD1234ULL);
static constexpr uint64_t GL_P = 0xFFFFFFFF00000001ULL;

static uint64_t rand_field() {
    return rng() % GL_P;
}

// ----- File loading ----------------------------------------------------------
static std::string read_file(const char* path) {
    std::ifstream f(path);
    if (!f) {
        fprintf(stderr, "Cannot open: %s\n", path);
        return "";
    }
    std::ostringstream ss;
    ss << f.rdbuf();
    return ss.str();
}

// ----- Test kernel appended on top of library source -------------------------
static const char* KERNEL_BODY = R"(
// pod12_test: one thread per hash; reads 12 ulongs from in[tid*12..],
// runs pod12, canonicalizes, writes 12 ulongs to out[tid*12..].
kernel void pod12_test(
    device const ulong* inp [[ buffer(0) ]],
    device       ulong* out [[ buffer(1) ]],
    uint tid [[ thread_position_in_grid ]]
) {
    ulong st[12];
    for (int i = 0; i < 12; i++) st[i] = inp[tid * 12 + i];
    pod12(st);
    for (int i = 0; i < 12; i++) out[tid * 12 + i] = gl_canonicalize(st[i]);
}
)";

// ----- Main ------------------------------------------------------------------
int main() {
    // 1. Get Metal device
    id<MTLDevice> device = MTLCreateSystemDefaultDevice();
    if (!device) {
        printf("probe_poseidon: no Metal device\n");
        return 1;
    }
    printf("probe_poseidon: device = %s\n", [[device name] UTF8String]);

    // 2. Generate random inputs (1000 states * 12 elements)
    static constexpr int N = 1000;
    static constexpr int SW = 12;
    std::vector<uint64_t> inp_data(N * SW);
    for (int i = 0; i < N * SW; i++) {
        inp_data[i] = rand_field();
    }

    // 3. CPU oracle reference
    std::vector<uint64_t> cpu_out(N * SW);
    for (int i = 0; i < N; i++) {
        Goldilocks::Element state[SW];
        Goldilocks::Element input[SW];
        for (int j = 0; j < SW; j++) input[j].fe = inp_data[i * SW + j];
        PoseidonGoldilocks::hash_full_result_seq(state, input);
        for (int j = 0; j < SW; j++) cpu_out[i * SW + j] = state[j].fe;
    }

    // 4. Build Metal library from source (field.metal + constants.metal.inc + poseidon.metal + kernel)
    std::string kernel_dir = MTL_KERNEL_DIR;

    std::string field_src     = read_file((kernel_dir + "/field.metal").c_str());
    std::string constants_src = read_file((kernel_dir + "/constants.metal.inc").c_str());
    std::string poseidon_src  = read_file((kernel_dir + "/poseidon.metal").c_str());

    if (field_src.empty() || constants_src.empty() || poseidon_src.empty()) {
        fprintf(stderr, "probe_poseidon: failed to load kernel sources\n");
        return 1;
    }

    // The poseidon.metal uses #include directives but we inline to avoid
    // Metal compiler path resolution issues in runtime compilation.
    // Strip the #include lines and concatenate directly.
    auto strip_includes = [](const std::string& src) -> std::string {
        std::istringstream in(src);
        std::ostringstream out;
        std::string line;
        while (std::getline(in, line)) {
            if (line.find("#include") != std::string::npos) continue;
            out << line << "\n";
        }
        return out.str();
    };

    std::string full_src =
        "#include <metal_stdlib>\n"
        "using namespace metal;\n"
        + strip_includes(field_src)
        + strip_includes(constants_src)
        + strip_includes(poseidon_src)
        + std::string(KERNEL_BODY);

    NSString* src_ns = [NSString stringWithUTF8String:full_src.c_str()];
    NSError* err = nil;
    id<MTLLibrary> library = [device newLibraryWithSource:src_ns
                                                  options:nil
                                                    error:&err];
    if (!library) {
        printf("probe_poseidon: compile error:\n%s\n",
               [[err localizedDescription] UTF8String]);
        // Print first 2000 chars of source for debugging
        printf("--- source (first 2000 chars) ---\n%.*s\n---\n",
               2000, full_src.c_str());
        return 1;
    }

    id<MTLFunction> fn = [library newFunctionWithName:@"pod12_test"];
    if (!fn) {
        printf("probe_poseidon: kernel 'pod12_test' not found\n");
        return 1;
    }

    NSError* psoErr = nil;
    id<MTLComputePipelineState> pso =
        [device newComputePipelineStateWithFunction:fn error:&psoErr];
    if (!pso) {
        printf("probe_poseidon: PSO error: %s\n",
               [[psoErr localizedDescription] UTF8String]);
        return 1;
    }

    // 5. MTL buffers
    id<MTLBuffer> inp_buf = [device newBufferWithBytes:inp_data.data()
                                                length:N * SW * sizeof(uint64_t)
                                               options:MTLResourceStorageModeShared];
    id<MTLBuffer> out_buf = [device newBufferWithLength:N * SW * sizeof(uint64_t)
                                                options:MTLResourceStorageModeShared];

    // 6. Dispatch
    id<MTLCommandQueue> queue = [device newCommandQueue];
    id<MTLCommandBuffer> cmd  = [queue commandBuffer];
    id<MTLComputeCommandEncoder> enc = [cmd computeCommandEncoder];
    [enc setComputePipelineState:pso];
    [enc setBuffer:inp_buf offset:0 atIndex:0];
    [enc setBuffer:out_buf offset:0 atIndex:1];

    NSUInteger tgSize = MIN((NSUInteger)N, pso.maxTotalThreadsPerThreadgroup);
    [enc dispatchThreads:MTLSizeMake(N, 1, 1)
      threadsPerThreadgroup:MTLSizeMake(tgSize, 1, 1)];
    [enc endEncoding];
    [cmd commit];
    [cmd waitUntilCompleted];

    // 7. Compare
    const uint64_t* gpu_out = (const uint64_t*)[out_buf contents];
    int mismatches = 0;

    for (int i = 0; i < N; i++) {
        for (int j = 0; j < SW; j++) {
            uint64_t gpu_val = gpu_out[i * SW + j];
            uint64_t cpu_val = cpu_out[i * SW + j];
            if (gpu_val != cpu_val) {
                if (mismatches == 0) {
                    printf("MISMATCH at state=%d element=%d:\n", i, j);
                    printf("  gpu=0x%016llx  cpu=0x%016llx\n",
                           (unsigned long long)gpu_val,
                           (unsigned long long)cpu_val);
                    printf("  Input state %d:\n", i);
                    for (int k = 0; k < SW; k++) {
                        printf("    [%2d] 0x%016llx\n", k,
                               (unsigned long long)inp_data[i * SW + k]);
                    }
                }
                mismatches++;
            }
        }
    }

    if (mismatches == 0) {
        printf("probe_poseidon: PASS — all %d Poseidon12 states bit-exact\n", N);
        return 0;
    } else {
        printf("probe_poseidon: FAIL — %d element mismatches across %d states\n",
               mismatches, N);
        return 1;
    }
}
