#ifndef GOLDILOCKS3_FFI_HPP
#define GOLDILOCKS3_FFI_HPP
    #include "goldilocks_cubic_extension.hpp"

    // BASIC FIELD OPERATIONS

    static inline const Element &zero() { return ZERO; };
    static inline void zero(Element &result)
    static inline const Element &one() { return ONE; };
    static inline void one(Element &result)
    static inline bool isOne(Element &result)
    static void copy(Element &dst, const Element &src)
    static void copy(Element *dst, const Element *src)
    static void copy_batch(Goldilocks::Element *dst, const Goldilocks::Element *src)
    static void copy_avx(Goldilocks::Element *dst, const __m256i a0_, const __m256i a1_, const __m256i a2_)
    static inline void fromU64(Element &result, uint64_t in1[FIELD_EXTENSION])
    static inline void fromS32(Element &result, int32_t in1[FIELD_EXTENSION])
    static inline void toU64(uint64_t (&result)[FIELD_EXTENSION], const Element &in1)
    static inline std::vector<Goldilocks::Element> toVector(const Element &in1)
    static inline std::vector<Goldilocks::Element> toVector(const Element *in1)
    static inline std::string toString(const Element &in1, int radix = 10)
    static inline void toString(std::string &result, const Element &in1, int radix = 10)
    static inline void toString(std::string (&result)[FIELD_EXTENSION], const Element &in1, int radix = 10)
    static std::string toString(const Element *in1, const uint64_t size, int radix)
    static inline void fromString(Element &result, const std::string (&in1)[FIELD_EXTENSION], int radix = 10)

#ifdef __AVX512__
    static void copy_avx512(Goldilocks::Element *dst, const __m512i a0_, const __m512i a1_, const __m512i a2_)
#endif
    // ======== ADD ========
    static inline void add(Element &result, const Element &a, const uint64_t &b)
    static inline void add(Element &result, const Element &a, const Goldilocks::Element b)
    static inline void add(Element &result, const Goldilocks::Element a, const Element &b)
    static inline void add(Element &result, const Element &a, const Element &b)
    static inline void add_batch(Goldilocks::Element *result, const Goldilocks::Element *a, const Goldilocks::Element *b)
    static inline void add_batch(Goldilocks::Element *result, const Goldilocks::Element *a, const Goldilocks::Element *b, uint64_t stride_a, uint64_t stride_b)
    static inline void add31_batch(Goldilocks::Element *result, const Goldilocks::Element *a, const Goldilocks::Element *b, uint64_t stride_a, uint64_t stride_b)
    static inline void add13_batch(Goldilocks::Element *result, const Goldilocks::Element *a, const Goldilocks::Element *b)
    static inline void add1c3c_batch(Goldilocks::Element *result, const Goldilocks::Element a, const Goldilocks::Element *b)
    static inline void add13c_batch(Goldilocks::Element *result, const Goldilocks::Element *a, const Goldilocks::Element *b)
    static inline void add13_batch(Goldilocks::Element *result, const Goldilocks::Element *a, const Goldilocks::Element *b, uint64_t offset_a, uint64_t offset_b)
    static inline void add13c_batch(Goldilocks::Element *result, const Goldilocks::Element *a, const Goldilocks::Element *b, uint64_t offset_a)
    static inline void add33c_batch(Goldilocks::Element *result, const Goldilocks::Element *a, const Goldilocks::Element *b)
    static inline void add33c_batch(Goldilocks::Element *result, Goldilocks::Element *a, Goldilocks::Element *b, uint64_t stride_a)
    static inline void add_avx(Goldilocks::Element *result, const Goldilocks::Element *a, const Goldilocks::Element *b)
    static inline void add_avx(Goldilocks::Element *result, const Goldilocks::Element *a, const Goldilocks::Element *b, uint64_t stride_a, uint64_t stride_b)
    static inline void add31_avx(Goldilocks::Element *result, Goldilocks::Element *a, const Goldilocks::Element *b, uint64_t stride_a, uint64_t stride_b)
    static inline void add13_avx(Goldilocks::Element *result, Goldilocks::Element *a, const Goldilocks::Element *b)
    static inline void add1c3c_avx(Goldilocks::Element *result, const Goldilocks::Element a, const Goldilocks::Element *b)
    static inline void add13c_avx(Goldilocks::Element *result, const Goldilocks::Element *a, const Goldilocks::Element *b)
    static inline void add13_avx(Goldilocks::Element *result, const Goldilocks::Element *a, const Goldilocks::Element *b, uint64_t offset_a, uint64_t offset_b)
    static inline void add13c_avx(Goldilocks::Element *result, const Goldilocks::Element *a, const Goldilocks::Element *b, uint64_t offset_a)
    static inline void add33c_avx(Goldilocks::Element *result, const Goldilocks::Element *a, const Goldilocks::Element *b)
    static inline void add33c_avx(Goldilocks::Element *result, Goldilocks::Element *a, Goldilocks::Element *b, uint64_t stride_a)
    static inline void add13_avx(Goldilocks::Element *result, const __m256i &a_, const Goldilocks::Element *b)
    static inline void add13c_avx(Goldilocks::Element *result, const __m256i &a_, const Goldilocks::Element *b)
    static inline void add13_avx(Goldilocks3::Element_avx c_, const __m256i &a_, Goldilocks3::Element_avx b_)
    static inline void add13c_avx(Goldilocks3::Element_avx c_, const __m256i &a_, const Goldilocks::Element *b)
    static inline void add1c3c_avx(Goldilocks3::Element_avx c_, const Goldilocks::Element a, const Goldilocks::Element *b)
    static inline void add13_avx(Goldilocks3::Element_avx c_, const Goldilocks::Element *a, Goldilocks3::Element_avx b_, uint64_t offset_a)
    static inline void add13c_avx(Goldilocks3::Element_avx c_, const Goldilocks::Element *a, const Goldilocks::Element *b, uint64_t offset_a)
    static inline void add_avx(Goldilocks3::Element_avx c_, Goldilocks3::Element_avx a_, Goldilocks3::Element_avx b_)
    static inline void add33c_avx(Goldilocks3::Element_avx c_, Goldilocks3::Element_avx a_, const Goldilocks::Element *b)
    static inline void add_avx(Goldilocks3::Element_avx c_, const Goldilocks::Element *a, Goldilocks3::Element_avx b_, uint64_t stride_a)
    static inline void add33c_avx(Goldilocks3::Element_avx c_, Goldilocks::Element *a, Goldilocks::Element *b, uint64_t stride_a)
    static inline void add13_avx(Goldilocks::Element *c, uint64_t stride_c, const __m256i &a_, Goldilocks3::Element_avx b_)
    static inline void add_avx(Goldilocks::Element *c, uint64_t stride_c, const Goldilocks::Element *a, Goldilocks3::Element_avx b_, uint64_t stride_a)
    static inline void add_avx(Goldilocks::Element *c, uint64_t stride_c, Goldilocks3::Element_avx a_, Goldilocks3::Element_avx b_)
    static inline void add33c_avx(Goldilocks::Element *c, uint64_t stride_c, Goldilocks3::Element_avx a_, const Goldilocks::Element *b)
    static inline void add13_avx(Goldilocks::Element *c, uint64_t stride_c[4], const __m256i &a_, Goldilocks3::Element_avx b_)
    static inline void add_avx(Goldilocks::Element *c, uint64_t stride_c[4], const Goldilocks::Element *a, Goldilocks3::Element_avx b_, uint64_t stride_a)
    static inline void add33c_avx(Goldilocks::Element *c, uint64_t stride_c[4], Goldilocks3::Element_avx a_, const Goldilocks::Element *b)
    static inline void add_avx(__m256i &c0_, __m256i &c1_, __m256i &c2_, const __m256i a0_, const __m256i a1_, const __m256i a2_, const __m256i b0_, const __m256i b1_, const __m256i b2_)
    static inline void add_avx(__m256i &c0_, __m256i &c1_, __m256i &c2_, const __m256i a0_, const __m256i a1_, const __m256i a2_, const Goldilocks::Element *b, uint64_t stride)
    static inline void add31_avx(__m256i &c0_, __m256i &c1_, __m256i &c2_, __m256i a0_, const __m256i a1_, const __m256i a2_, const Goldilocks::Element *b, uint64_t stride)

#ifdef __AVX512__
    static inline void add13_avx512(Goldilocks3::Element_avx512 c_, const __m512i &a_, Goldilocks3::Element_avx512 b_)
    static inline void add13c_avx512(Goldilocks3::Element_avx512 c_, const __m512i &a_, const Goldilocks::Element *b)
    static inline void add1c3c_avx512(Goldilocks3::Element_avx512 c_, const Goldilocks::Element a, const Goldilocks::Element *b)
    static inline void add13_avx512(Goldilocks3::Element_avx512 c_, const Goldilocks::Element *a, Goldilocks3::Element_avx512 b_, uint64_t offset_a)
    static inline void add13c_avx512(Goldilocks3::Element_avx512 c_, const Goldilocks::Element *a, const Goldilocks::Element *b, uint64_t offset_a)
    static inline void add_avx512(Goldilocks3::Element_avx512 c_, Goldilocks3::Element_avx512 a_, Goldilocks3::Element_avx512 b_)
    static inline void add33c_avx512(Goldilocks3::Element_avx512 c_, Goldilocks3::Element_avx512 a_, const Goldilocks::Element *b)
    static inline void add_avx512(Goldilocks3::Element_avx512 c_, const Goldilocks::Element *a, Goldilocks3::Element_avx512 b_, uint64_t stride_a)
    static inline void add33c_avx512(Goldilocks3::Element_avx512 c_, Goldilocks::Element *a, Goldilocks::Element *b, uint64_t stride_a)
    static inline void add13_avx512(Goldilocks::Element *c, uint64_t stride_c, const __m512i &a_, Goldilocks3::Element_avx512 b_)
    static inline void add_avx512(Goldilocks::Element *c, uint64_t stride_c, const Goldilocks::Element *a, Goldilocks3::Element_avx512 b_, uint64_t stride_a)
    static inline void add33c_avx512(Goldilocks::Element *c, uint64_t stride_c, Goldilocks3::Element_avx512 a_, const Goldilocks::Element *b)
    static inline void add13_avx512(Goldilocks::Element *c, uint64_t stride_c[AVX512_SIZE_], const __m512i &a_, Goldilocks3::Element_avx512 b_)
    static inline void add_avx512(Goldilocks::Element *c, uint64_t stride_c[AVX512_SIZE_], const Goldilocks::Element *a, Goldilocks3::Element_avx512 b_, uint64_t stride_a)
    static inline void add33c_avx512(Goldilocks::Element *c, uint64_t stride_c[AVX512_SIZE_], Goldilocks3::Element_avx512 a_, const Goldilocks::Element *b)
    static inline void add_avx512(__m512i &c0_, __m512i &c1_, __m512i &c2_, const __m512i a0_, const __m512i a1_, const __m512i a2_, const __m512i b0_, const __m512i b1_, const __m512i b2_)
    static inline void add_avx512(__m512i &c0_, __m512i &c1_, __m512i &c2_, const __m512i a0_, const __m512i a1_, const __m512i a2_, const Goldilocks::Element *b, uint64_t stride)
    static inline void add31_avx512(__m512i &c0_, __m512i &c1_, __m512i &c2_, __m512i a0_, const __m512i a1_, const __m512i a2_, const Goldilocks::Element *b, uint64_t stride)
#endif

    // ======== SUB ========
    static inline void sub(Element &result, Element &a, uint64_t &b)
    static inline void sub(Element &result, Goldilocks::Element a, Element &b)
    static inline void sub(Element &result, Element &a, Goldilocks::Element b)
    static inline void sub(Element &result, Element &a, Element &b)
    static inline void sub13c_batch(Goldilocks::Element *result, Goldilocks::Element *a, Goldilocks::Element *b, uint64_t stride_a)
    static inline void sub33c_batch(Goldilocks::Element *result, Goldilocks::Element *a, Goldilocks::Element *b, uint64_t stride_a)
    static inline void sub31_batch(Goldilocks::Element *result, Goldilocks::Element *a, Goldilocks::Element *b, uint64_t stride_a, uint32_t stride_b)
    static inline void sub31c_batch(Goldilocks::Element *result, Goldilocks::Element *a, Goldilocks::Element b, uint64_t stride_a)
    static inline void sub_batch(Goldilocks::Element *result, Goldilocks::Element *a, Goldilocks::Element *b)
    static inline void sub33c_batch(Goldilocks::Element *result, Goldilocks::Element *a, Goldilocks::Element *b)
    static inline void sub_batch(Goldilocks::Element *result, Goldilocks::Element *a, Goldilocks::Element *b, uint64_t stride_a, uint64_t stride_b)
    static inline void sub33c_avx(Goldilocks::Element *result, Goldilocks::Element *a, Goldilocks::Element *b, uint64_t stride_a)
    static inline void sub31_avx(Goldilocks::Element *result, Goldilocks::Element *a, Goldilocks::Element *b, uint64_t stride_a, uint32_t stride_b)
    static inline void sub31c_avx(Goldilocks::Element *result, Goldilocks::Element *a, Goldilocks::Element b, uint64_t stride_a)
    static inline void sub_avx(Goldilocks::Element *result, Goldilocks::Element *a, Goldilocks::Element *b)
    static inline void sub33c_avx(Goldilocks::Element *result, Goldilocks::Element *a, Goldilocks::Element *b)
    static inline void sub_avx(Goldilocks::Element *result, Goldilocks::Element *a, Goldilocks::Element *b, uint64_t stride_a, uint64_t stride_b)
    static inline void sub31c_avx(Goldilocks3::Element_avx &c_, Goldilocks::Element *a, Goldilocks::Element b, const uint64_t stride_a[4])
    static inline void sub31c_avx(Goldilocks3::Element_avx &c_, Goldilocks::Element *a, Goldilocks::Element b, uint64_t stride_a)
    static inline void sub_avx(Goldilocks3::Element_avx &c_, Goldilocks3::Element_avx a_, Goldilocks3::Element_avx b_)
    static inline void sub33c_avx(Goldilocks3::Element_avx &c_, Goldilocks3::Element_avx a_, Goldilocks::Element *b)
    static inline void sub33c_avx(Goldilocks::Element *c, uint64_t stride_c, Goldilocks3::Element_avx a_, Goldilocks3::Element_avx b_)
    static inline void sub_avx(Goldilocks3::Element_avx &c_, Goldilocks3::Element_avx a_, Goldilocks::Element *b, uint64_t stride_b)
    static inline void sub33c_avx(Goldilocks3::Element_avx &c_, Goldilocks::Element *a, Goldilocks::Element *b, uint64_t stride_a)
    static inline void sub13c_avx(__m256i &c0_, __m256i &c1_, __m256i &c2_, Goldilocks::Element *a, Goldilocks::Element *b, uint64_t stride_a)
    static inline void sub33c_avx(__m256i &c0_, __m256i &c1_, __m256i &c2_, Goldilocks::Element *a, Goldilocks::Element *b, uint64_t stride_a)

#ifdef __AVX512__
    static inline void sub31c_avx512(Goldilocks3::Element_avx512 &c_, Goldilocks::Element *a, Goldilocks::Element b, uint64_t stride_a)
    static inline void sub_avx512(Goldilocks3::Element_avx512 &c_, Goldilocks3::Element_avx512 a_, Goldilocks3::Element_avx512 b_)
    static inline void sub33c_avx512(Goldilocks3::Element_avx512 &c_, Goldilocks3::Element_avx512 a_, Goldilocks::Element *b)
    static inline void sub_avx512(Goldilocks3::Element_avx512 &c_, Goldilocks3::Element_avx512 a_, Goldilocks::Element *b, uint64_t stride_b)
    static inline void sub33c_avx512(Goldilocks3::Element_avx512 &c_, Goldilocks::Element *a, Goldilocks::Element *b, uint64_t stride_a)
    static inline void sub13c_avx512(__m512i &c0_, __m512i &c1_, __m512i &c2_, Goldilocks::Element *a, Goldilocks::Element *b, uint64_t stride_a)
    static inline void sub33c_avx512(__m512i &c0_, __m512i &c1_, __m512i &c2_, Goldilocks::Element *a, Goldilocks::Element *b, uint64_t stride_a)
#endif

    // ======== NEG ========
    static inline void neg(Element &result, Element &a)

    // ======== MUL ========
    static inline void mul(Element *result, Element *a, Element *b)
    static inline void mul(Element &result, Element &a, Element &b)
    static inline void mul(Element &result, Element &a, Goldilocks::Element &b)
    static inline void mul(Element &result, Goldilocks::Element a, Element &b)
    static inline void mul(Element &result, Element &a, uint64_t b)
    static inline void mul13c_batch(Goldilocks::Element *result, Goldilocks::Element *a, Element &b, uint64_t stride_a)
    static inline void mul1c3c_batch(Goldilocks::Element *result, Goldilocks::Element a, Element &b)
    static inline void mul13c_batch(Goldilocks::Element *result, Goldilocks::Element *a, Element &b, const uint64_t stride_a[4])
    static inline void mul_batch(Goldilocks::Element *result, Goldilocks::Element *a, Goldilocks::Element *b, Goldilocks::Element b_[3])
    static inline void mul_batch(Goldilocks::Element *result, Goldilocks::Element *a, Goldilocks::Element *b)
    static inline void mul33c_batch(Goldilocks::Element *result, Goldilocks::Element *a, Goldilocks::Element *b)
    static inline void mul_batch(Goldilocks::Element *result, Goldilocks::Element *a, Goldilocks::Element *b, uint64_t stride0, uint64_t stride1)
    static inline void mul_batch(Goldilocks::Element *result, Goldilocks::Element *a, Goldilocks::Element *b, const uint64_t stride0[4], const uint64_t stride1[4])
    static inline void mul33c_batch(Goldilocks::Element *result, Goldilocks::Element *a, Goldilocks::Element *b, uint64_t stride_a)
    static inline void mul33c_batch(Goldilocks::Element *result, Goldilocks::Element *a, Goldilocks::Element *b, const uint64_t stride_a[4])
    static inline void mul13c_batch(Goldilocks::Element *result, Goldilocks::Element *a, Goldilocks::Element *b)
    static inline void mul13_batch(Goldilocks::Element *result, Goldilocks::Element *a, Goldilocks::Element *b, uint64_t stride_a, uint64_t stride_b)
    static inline void mul13_batch(Goldilocks::Element *result, Goldilocks::Element *a, Goldilocks::Element *b, const uint64_t stride_a[4], const uint64_t stride_b[4])
    static inline void mul13c_avx(Goldilocks::Element *result, Goldilocks::Element *a, Element &b, uint64_t stride_a)
    static inline void mul1c3c_avx(Goldilocks::Element *result, Goldilocks::Element a, Element &b)
    static inline void mul13c_avx(Goldilocks::Element *result, Goldilocks::Element *a, Element &b, const uint64_t stride_a[4])
    static inline void mul_avx(Goldilocks::Element *result, Goldilocks::Element *a, Goldilocks::Element *b)
    static inline void mul33c_avx(Goldilocks::Element *result, Goldilocks::Element *a, Goldilocks::Element *b)
    static inline void mul_avx(Goldilocks::Element *result, Goldilocks::Element *a, Goldilocks::Element *b, uint64_t stride_a, uint64_t stride_b)
    static inline void mul_avx(Goldilocks::Element *result, Goldilocks::Element *a, Goldilocks::Element *b, const uint64_t stride_a[4], const uint64_t stride_b[4])
    static inline void mul33c_avx(Goldilocks::Element *result, Goldilocks::Element *a, Goldilocks::Element *b, uint64_t stride_a)
    static inline void mul33c_avx(Goldilocks::Element *result, Goldilocks::Element *a, Goldilocks::Element *b, const uint64_t stride_a[4])
    static inline void mul13c_avx(Goldilocks::Element *result, Goldilocks::Element *a, Goldilocks::Element *b)
    static inline void mul13_avx(Goldilocks::Element *result, Goldilocks::Element *a, Goldilocks::Element *b, uint64_t stride_a, uint64_t stride_b)
    static inline void mul13_avx(Goldilocks::Element *result, Goldilocks::Element *a, Goldilocks::Element *b, const uint64_t stride_a[4], const uint64_t stride_b[4])
    static inline void mul13c_avx(Goldilocks::Element *result, const __m256i &a_, Goldilocks::Element *b)
    static inline void mul13_avx(Goldilocks::Element *result, const __m256i &a_, Goldilocks::Element *b)
    static inline void mul13c_avx(Goldilocks3::Element_avx &c_, const __m256i &a_, Goldilocks::Element *b)
    static inline void mul13_avx(Goldilocks3::Element_avx &c_, const __m256i &a_, const Goldilocks3::Element_avx &b_)
    static inline void mul13_avx(Goldilocks3::Element_avx &c_, Goldilocks::Element *a, Goldilocks3::Element_avx b_, uint64_t stride_a)
    static inline void mul13c_avx(Goldilocks3::Element_avx &c_, Goldilocks::Element *a, Goldilocks::Element *b, uint64_t stride_a)
    static inline void mul13c_avx(Goldilocks3::Element_avx &c_, Goldilocks::Element *a, Goldilocks::Element *b, const uint64_t stride_a[4])
    static inline void mul13_avx(Goldilocks3::Element_avx &c_, Goldilocks::Element *a, Goldilocks3::Element_avx b_, const uint64_t stride_a[4])
    static inline void mul1c3c_avx(Goldilocks3::Element_avx &c_, Goldilocks::Element a, Element &b)
    static inline void mul33c_avx(Goldilocks3::Element_avx &c_, Goldilocks3::Element_avx &a_, Goldilocks::Element *b)
    static inline void mul_avx(Goldilocks3::Element_avx &c_, Goldilocks3::Element_avx &a_, Goldilocks3::Element_avx &b_)
    static inline void mul_avx(Goldilocks::Element *c, uint64_t stride_c, Goldilocks::Element *a, Goldilocks3::Element_avx &b_, uint64_t stride_a)
    static inline void mul_avx(Goldilocks::Element *c, uint64_t stride_c, Goldilocks3::Element_avx &a_, Goldilocks3::Element_avx &b_)
    static inline void mul_avx(Goldilocks::Element *c, uint64_t stride_c[4], Goldilocks3::Element_avx &a_, Goldilocks3::Element_avx &b_)
    static inline void mul_avx(Goldilocks3::Element_avx &c_, Goldilocks::Element *a, Goldilocks::Element *b, uint64_t stride_a, uint64_t stride_b)
    static inline void mul33c_avx(Goldilocks3::Element_avx &c_, Goldilocks::Element *a, Goldilocks::Element *b, uint64_t stride_a)
    static inline void mul33c_avx(Goldilocks3::Element_avx &c_, Goldilocks::Element *a, Goldilocks::Element *b, const uint64_t stride_a[4])
    static inline void mul_avx(Goldilocks3::Element_avx &c_, Goldilocks::Element *a, Goldilocks3::Element_avx &b_, const uint64_t stride_a[4])
    static inline void mul_avx(Goldilocks3::Element_avx &c_, Goldilocks::Element *a, Goldilocks3::Element_avx &b_, const uint64_t stride_a)
    static inline void mul_avx(Goldilocks3::Element_avx &c_, Goldilocks::Element *a, Goldilocks::Element *b, const uint64_t stride_a[4], const uint64_t stride_b[4])
    static inline void mul13c_avx(__m256i &c0_, __m256i &c1_, __m256i &c2_, Goldilocks::Element *a, Element &b, uint64_t stride_a)
    static inline void mul_avx(__m256i &c0_, __m256i &c1_, __m256i &c2_, __m256i a0_, __m256i a1_, __m256i a2_, __m256i b0_, __m256i b1_, __m256i b2_, __m256i aux0_, __m256i aux1_, __m256i aux2_)
    static inline void mul_avx(__m256i &c0_, __m256i &c1_, __m256i &c2_, __m256i a0_, __m256i a1_, __m256i a2_, Goldilocks::Element *b)

#ifdef __AVX512__
    static inline void mul13c_avx512(Goldilocks3::Element_avx512 &c_, const __m512i &a_, Goldilocks::Element *b)
    static inline void mul13_avx512(Goldilocks3::Element_avx512 &c_, const __m512i &a_, const Goldilocks3::Element_avx512 &b_)
    static inline void mul13_avx512(Goldilocks3::Element_avx512 &c_, Goldilocks::Element *a, Goldilocks3::Element_avx512 b_, uint64_t stride_a)
    static inline void mul13c_avx512(Goldilocks3::Element_avx512 &c_, Goldilocks::Element *a, Goldilocks::Element *b, uint64_t stride_a)
    static inline void mul13c_avx512(Goldilocks3::Element_avx512 &c_, Goldilocks::Element *a, Goldilocks::Element *b, const uint64_t stride_a[AVX512_SIZE_])
    static inline void mul13_avx512(Goldilocks3::Element_avx512 &c_, Goldilocks::Element *a, Goldilocks3::Element_avx512 b_, const uint64_t stride_a[AVX512_SIZE_])
    static inline void mul1c3c_avx512(Goldilocks3::Element_avx512 &c_, Goldilocks::Element a, Element &b)
    static inline void mul33c_avx512(Goldilocks3::Element_avx512 &c_, Goldilocks3::Element_avx512 &a_, Goldilocks::Element *b)
    static inline void mul_avx512(Goldilocks3::Element_avx512 &c_, Goldilocks3::Element_avx512 &a_, Goldilocks3::Element_avx512 &b_)
    static inline void mul_avx512(Goldilocks::Element *c, uint64_t stride_c, Goldilocks3::Element_avx512 &a_, Goldilocks3::Element_avx512 &b_)
    static inline void mul_avx512(Goldilocks::Element *c, uint64_t stride_c[AVX512_SIZE_], Goldilocks3::Element_avx512 &a_, Goldilocks3::Element_avx512 &b_)
    static inline void mul_avx512(Goldilocks3::Element_avx512 &c_, Goldilocks::Element *a, Goldilocks::Element *b, uint64_t stride_a, uint64_t stride_b)
    static inline void mul33c_avx512(Goldilocks3::Element_avx512 &c_, Goldilocks::Element *a, Goldilocks::Element *b, uint64_t stride_a)
    static inline void mul33c_avx512(Goldilocks3::Element_avx512 &c_, Goldilocks::Element *a, Goldilocks::Element *b, const uint64_t stride_a[AVX512_SIZE_])
    static inline void mul_avx512(Goldilocks3::Element_avx512 &c_, Goldilocks::Element *a, Goldilocks3::Element_avx512 &b_, const uint64_t stride_a[AVX512_SIZE_])
    static inline void mul_avx512(Goldilocks3::Element_avx512 &c_, Goldilocks::Element *a, Goldilocks3::Element_avx512 &b_, const uint64_t stride_a)
    static inline void mul_avx512(Goldilocks3::Element_avx512 &c_, Goldilocks::Element *a, Goldilocks::Element *b, const uint64_t stride_a[AVX512_SIZE_], const uint64_t stride_b[AVX512_SIZE_])
    static inline void mul13c_avx512(__m512i &c0_, __m512i &c1_, __m512i &c2_, Goldilocks::Element *a, Element &b, uint64_t stride_a)
    static inline void mul_avx512(__m512i &c0_, __m512i &c1_, __m512i &c2_, __m512i a0_, __m512i a1_, __m512i a2_, __m512i b0_, __m512i b1_, __m512i b2_, __m512i aux0_, __m512i aux1_, __m512i aux2_)
    static inline void mul_avx512(__m512i &c0_, __m512i &c1_, __m512i &c2_, __m512i a0_, __m512i a1_, __m512i a2_, Goldilocks::Element *b)
#endif

    // ======== DIV ========
    static inline void div(Element &result, Element &a, Goldilocks::Element b)

    // ======== MULSCALAR ========
    static inline void mulScalar(Element &result, Element &a, std::string &b)

    // ======== SQUARE ========
    static inline void square(Element &result, Element &a)

    // ======== INV ========
    static inline void inv(Element *result, Element *a)
    static inline void inv(Element &result, Element &a)

    static void batchInverse(Goldilocks3::Element *res, Goldilocks3::Element *src, uint64_t size)
#endif