// tools/gen_metal_constants.cpp
// Build-time codegen: emits src/metal/kernels/constants.metal.inc from the
// single C++ source of truth in src/poseidon_goldilocks_constants.hpp.
//
// Canonical (non-Montgomery) tables only — USE_MONTGOMERY is hardcoded to 0
// at src/goldilocks_base_field.hpp:20.
//
// Compile: clang++ -std=c++17 -Isrc tools/gen_metal_constants.cpp -o gen_metal_constants
// Run:     ./gen_metal_constants src/metal/kernels/constants.metal.inc

#include <cstdio>
#include <cstdlib>

#include "poseidon_goldilocks_constants.hpp"

namespace GL = PoseidonGoldilocksConstants;

static void emit_array(FILE *out,
                       const char *decl,
                       const Goldilocks::Element *elems,
                       size_t count)
{
    std::fprintf(out, "%s = {\n", decl);
    for (size_t i = 0; i < count; ++i)
    {
        const char *sep = (i + 1 < count) ? "," : "";
        std::fprintf(out, "    0x%016llxUL%s\n",
                     (unsigned long long)elems[i].fe, sep);
    }
    std::fprintf(out, "};\n\n");
}

int main(int argc, char *argv[])
{
    const char *outpath = (argc >= 2) ? argv[1]
                                      : "src/metal/kernels/constants.metal.inc";
    FILE *out = std::fopen(outpath, "w");
    if (!out)
    {
        std::perror(outpath);
        return EXIT_FAILURE;
    }
    std::fprintf(out,
        "// Generated by tools/gen_metal_constants — DO NOT EDIT\n"
        "// Source of truth: src/poseidon_goldilocks_constants.hpp (#else block)\n"
        "\n");
    emit_array(out, "constant ulong C[118]",  GL::C,  118);
    emit_array(out, "constant ulong M_[144]", GL::M_, 144);
    emit_array(out, "constant ulong P_[144]", GL::P_, 144);
    emit_array(out, "constant ulong S[507]",  GL::S,  507);
    std::fclose(out);
    return EXIT_SUCCESS;
}
